spring.application.name=nameclassifier
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

genderize.base-url=https://api.genderize.io
agify.base-url=https://api.agify.io
nationalize.base-url=https://api.nationalize.io

spring.profiles.active=prod
enable.test.auth=${ENABLE_TEST_AUTH:false}