spring.application.name=nameclassifier
server.port=${PORT:8080}

genderize.base-url=https://api.genderize.io
agify.base-url=https://api.agify.io
nationalize.base-url=https://api.nationalize.io

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/nameclassifier?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC