spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

github.oauth.client-id=${GITHUB_CLIENT_ID}
github.oauth.client-secret=${GITHUB_CLIENT_SECRET}
github.oauth.redirect-uri=${GITHUB_REDIRECT_URI}
github.oauth.scope=read:user user:email

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=180000
jwt.refresh-token-expiration-ms=300000