spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

github.oauth.web.client-id=${GITHUB_WEB_CLIENT_ID}
github.oauth.web.client-secret=${GITHUB_WEB_CLIENT_SECRET}
github.oauth.web.redirect-uri=${GITHUB_WEB_REDIRECT_URI}

github.oauth.cli.client-id=${GITHUB_CLI_CLIENT_ID}
github.oauth.cli.client-secret=${GITHUB_CLI_CLIENT_SECRET}
github.oauth.cli.redirect-uri=${GITHUB_CLI_REDIRECT_URI}

github.oauth.scope=read:user user:email

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=180000
jwt.refresh-token-expiration-ms=300000

app.web.client.url=${WEB_CLIENT_URL}
app_cors_allowed_origins=${CORS_ALLOWED_ORIGINS}