spring.datasource.url=jdbc:mysql://localhost:3306/nameclassifier?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

github.oauth.client-id=
github.oauth.client-secret=
github.oauth.redirect-uri=http://localhost:8080/auth/github/callback
github.oauth.scope=read:user user:email

jwt.secret=
jwt.access-token-expiration-ms=180000
jwt.refresh-token-expiration-ms=300000